### ISSUE TITLE
Create senza deployment setup

### ISSUE THREAD

**Issue by jcranky** [jcranky/scalatron#2]

**Comment by andreikaigorodov** [comment]
Maybe, it is also worth to try that new zalando kubernetes-based deployment setup (if someone is interested in it.

**Comment by jcranky** [comment]
True , did anyone do that Training?

**Comment by jcranky** [comment]
I'm reading a bit about how to use our kubernetes thingy, lets see if we can use it without really touching the project.

**Comment by jcranky** [comment]
I'll close this issue since it is specific to our internal case and will now aggregate to the OS part of the project here.
