### ISSUE TITLE
extract dependencies to a specific sbt file

### ISSUE THREAD

**Issue by jcranky** [jcranky/scalatron#6]
Something like `depend.sbt`, so that the build file itself is cleaner and easier to read.

**Comment by jmhofer** [comment]
Maybe as `project/Dependencies.scala`? - at least iirc a file named `depend.sbt` will be read only after `build.sbt`.

**Comment by jcranky** [comment]
@jmhofer I'm not sure about the read order, but we use this in our projects and it seems to work fine :)
